name: football_stats
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blinker=1.9.0=pyhff2d567_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - click=8.3.1=pyh707e725_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-sqlalchemy=3.1.1=pyh29332c3_1
  - greenlet=3.2.4=py314he8615de_1
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - libcxx=21.1.6=hf598326_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - markupsafe=3.0.3=pyh7db6752_0
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.0=h40d2674_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h1d1bf99_2
  - sqlalchemy=2.0.44=py314h0612a62_0
  - tk=8.6.13=h892fb3f_3
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - bcrypt==5.0.0
      - flask-bcrypt==1.0.1
      - flask-login==0.6.3
      - psycopg2-binary==2.9.11
      - pyjwt==2.10.1
prefix: /Users/cameronolivier/miniconda3/envs/football_stats
